version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: ${version}
    commands:
      - dotnet --version

  pre_build:
    commands:
      - echo "Restoring dependencies..."
      - dotnet restore

  build:
    commands:
      - echo "Building the project..."
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo "Publishing..."
      - dotnet publish -c Release -o ./publish

artifacts:
  files:
    - './publish/**/*'
