version: 0.2

phases:
  install:
    runtime-versions:
      golang: ${version}
    commands:
      - go version

  pre_build:
    commands:
      - echo "Fetching dependencies..."
      - go mod download

  build:
    commands:
      - echo "Building the Go application..."
      - go build -o myapp ./...

  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - myapp
