version: 0.2

phases:
  install:
    runtime-versions:
      python: ${version}
    commands:
      - python --version
      - pip --version
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Pre-build steps..."

  build:
    commands:
      - echo "Building..."

  post_build:
    commands:
      - echo "Post-build steps..."

artifacts:
  files:
    - '**/*'
